# Generated by Django 5.2.15 on 2026-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('province', models.IntegerField(default=0)),
                ('district', models.IntegerField(default=0)),
                ('commune', models.IntegerField(default=0)),
                ('village', models.IntegerField(default=0)),
            ],
        ),
    ]
